# /etc/ssh/sshd_config.d/95-harden-ssh.conf
# Managed by deb-harden-ssh package

AllowTcpForwarding no
ClientAliveCountMax 2
ClientAliveInterval 300
GatewayPorts no
IgnoreRhosts yes
KbdInteractiveAuthentication no
LoginGraceTime 30
LogLevel VERBOSE
MaxAuthTries 3
MaxSessions 2
PasswordAuthentication no
PermitEmptyPasswords no
PermitRootLogin prohibit-password
PermitTunnel no
PrintLastLog yes
StrictModes yes
TCPKeepAlive no
UseDNS no
X11Forwarding no
DisableForwarding yes
AllowAgentForwarding no
AllowGroups ssh-users sudo
